version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: postgres   
      POSTGRES_DB: postgres   
    ports:
      - "5432:5432"             
    volumes:
      - postgres_data:/var/lib/postgresql/data
  app:
    build: .
    depends_on:
      - db
    volumes:
      - .:/app
    ports:
      - "5000:5000"
volumes:
  postgres_data: